[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
solc_version = "0.8.17"
evm_version = "london"

# File system permissions
fs_permissions = [
    { access = "read-write", path = "./" },
    { access = "read-write", path = "./deployment-arbitrum.txt" },
    { access = "read-write", path = "./cache/" },
    { access = "read-write", path = "./out/" }
]

# RPC endpoints
[rpc_endpoints]
arbitrum = "https://arb1.arbitrum.io/rpc"
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"

# Etherscan API keys
[etherscan]
arbitrum = { key = "VD3HX86J6TITE1WVT9HEESQ7AIPE11MCI5" }
arbitrum_sepolia = { key = "VD3HX86J6TITE1WVT9HEESQ7AIPE11MCI5" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
